language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
  - yarn --ignore-engines
script: 
  - yarn add travis-up
before_deploy:
  - ./bin/up version
deploy:
  provider: script
  script: ./bin/up deploy production
  skip_cleanup: true

env:
  global:
    AWS_REGION: us-east-1